{% set name = "realalg" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/realalg-{{ version }}.tar.gz
  sha256: 049b8ab342484fb596fadef7304dffac1322f43f1944130ca48d49c56b42144f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.15.1
    - sympy >=1.6
    - cypari2 >=2,<3
    # We need Cython at runtime since it is an install_requires of our indirect
    # dependency cysignals, fixed in
    # https://github.com/conda-forge/cysignals-feedstock/pull/44
    - cython

test:
  imports:
    - realalg
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MarkCBell/realalg
  summary: Computations with real algebraic numbers
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - saraedum
